###
# Register

POST http://127.0.0.1:8000/api/register/
content-type: application/json

{
    "name": "amtech",
    "email": "abdulsalamamtech@gmail.com",
    "password": "12345678",
    "password_confirmation": "12345678",
    "first_name": "amtech",
    "last_name": "digital",
    "security_question": "what is your name",
    "answer": "amtech"
}



###
# Login
POST http://127.0.0.1:8000/api/login/
content-type: application/json

{
    "email": "abdulsalamamtech@gmail.com",
    "password": "12345678"
}



###
# Logout
POST http://127.0.0.1:8000/api/logout/
content-type: application/json
Authorization: Bearer 5|WHSt2cQUi3Rl6BvdjJFMxApEzV4kKpyxmJ1I3t0iafbff6d


###
# Get login user information
GET http://127.0.0.1:8000/api/user/
content-type: application/json
Authorization: Bearer 6|Rvmt8fPs4HDBlJty6vpQ9jq2Aq0PUEjD1pfCX1S43c4afbdc



###
# Get login user profile
# GET http://127.0.0.1:8000/api/info
# content-type: application/json
# Authorization: Bearer 6|UI83SlqBp1WEr8bVHi7m8bOVl1vfUV0LZssrfmq0f48d6b9a


********************************


###
# Get user profile information
GET http://127.0.0.1:8000/api/profile
content-type: application/json
Authorization: Bearer 6|Rvmt8fPs4HDBlJty6vpQ9jq2Aq0PUEjD1pfCX1S43c4afbdc


###
# Update user profile information
PUT http://127.0.0.1:8000/api/profile
content-type: application/json
Authorization: Bearer 6|UI83SlqBp1WEr8bVHi7m8bOVl1vfUV0LZssrfmq0f48d6b9a

{
    "phone_number": "+2349091929394",
    "gender": "male",
    "dob": "2002-09-01"
}


###
# Get user social media information
GET http://127.0.0.1:8000/api/profile/socials/
content-type: application/json
Authorization: Bearer 6|Rvmt8fPs4HDBlJty6vpQ9jq2Aq0PUEjD1pfCX1S43c4afbdc



###
# Update user social media information
PUT http://127.0.0.1:8000/api/profile/socials/
content-type: application/json
Authorization: Bearer 6|Rvmt8fPs4HDBlJty6vpQ9jq2Aq0PUEjD1pfCX1S43c4afbdc

{
    "facebook": "https://www.facebook.com/amtech",
    "github": "https://github.com/amtech",
    "twitter": "https://twitter.com/amtech/"
}




********************************



###
# Get all certificate
GET http://127.0.0.1:8000/api/certificates
content-type: application/json
Authorization: Bearer 6|Rvmt8fPs4HDBlJty6vpQ9jq2Aq0PUEjD1pfCX1S43c4afbdc


###
# Create certificate
POST http://127.0.0.1:8000/api/certificates
content-type: application/json
Authorization: Bearer 6|Rvmt8fPs4HDBlJty6vpQ9jq2Aq0PUEjD1pfCX1S43c4afbdc

{
    "belong_to": 1,
    "certificate": "binary image file",
    "course": "project management",
    "description": "3month project management course"
}


###
# Update certificate
PUT http://127.0.0.1:8000/api/certificates/1
content-type: application/json
Authorization: Bearer 6|Rvmt8fPs4HDBlJty6vpQ9jq2Aq0PUEjD1pfCX1S43c4afbdc

{
    "certificate": "binary image file",
    "course": "project management",
    "description": "3month project management course"
}



********************************



###
# Get all Projects

GET http://127.0.0.1:8000/api/projects
content-type: application/json




###
# Get personal Projects

GET http://127.0.0.1:8000/api/profile/projects
content-type: application/json
Authorization: Bearer 6|Rvmt8fPs4HDBlJty6vpQ9jq2Aq0PUEjD1pfCX1S43c4afbdc


###
# Get one Project

GET http://127.0.0.1:8000/api/projects/3
content-type: application/json


###
# Create Projects

POST http://127.0.0.1:8000/api/projects
content-type: application/json
Authorization: Bearer 6|Rvmt8fPs4HDBlJty6vpQ9jq2Aq0PUEjD1pfCX1S43c4afbdc

{
    "banner": "banary image file",
    "title": "Amtech's First Project",
    "description": "This is my first project",
    "category": "Web Development",
    "video_url": "https://www.youtube.com/shorts/wGoJEWZuixg?feature=share",
    "category": "link",
    "tags": "dev, project, first",
    "status": "public"
}



###
# Like Projects (need some modification)

PUT http://127.0.0.1:8000/api/projects/4/likes
content-type: application/json
Authorization: Bearer 6|Rvmt8fPs4HDBlJty6vpQ9jq2Aq0PUEjD1pfCX1S43c4afbdc




###
# Share Projects

PUT http://127.0.0.1:8000/api/projects/3/shares
content-type: application/json
Authorization: Bearer 6|Rvmt8fPs4HDBlJty6vpQ9jq2Aq0PUEjD1pfCX1S43c4afbdc




###
# Update Project (need to be dubug)

PUT  http://127.0.0.1:8000/api/projects/3
content-type: application/json
Authorization: Bearer 6|Rvmt8fPs4HDBlJty6vpQ9jq2Aq0PUEjD1pfCX1S43c4afbdc

{
    "title": "Amtech's First Project",
    "description": "This is my first project",
    "category": "Web Development",
    "video_url": "https://www.youtube.com/shorts/wGoJEWZuixg?feature=share",
    "likes": 2
}




********************************




###
# Get all Comments for a project

GET http://127.0.0.1:8000/api/projects/2/comments
content-type: application/json



###
# Create comment

POST http://127.0.0.1:8000/api/projects/4/comments
content-type: application/json
Authorization: Bearer 6|Rvmt8fPs4HDBlJty6vpQ9jq2Aq0PUEjD1pfCX1S43c4afbdc

{
    "content": "This is my first project comment"
}



###
# Update Comment (debug)

PUT http://127.0.0.1:8000/api/projects/2/comments/2
content-type: application/json
Authorization: Bearer 6|Rvmt8fPs4HDBlJty6vpQ9jq2Aq0PUEjD1pfCX1S43c4afbdc

{
    "content": "This is my first project",
}






********************************
