###
# Register

POST http://127.0.0.1:8000/api/register/
content-type: application/json

{
    "name": "amtech",
    "email": "abdulsalamamtech@gmail.com",
    "password": "12345678",
    "password_confirmation": "12345678",
    "first_name": "amtech",
    "last_name": "digital",
    "security_question": "what is your name",
    "answer": "amtech"
}



###
# Login
POST http://127.0.0.1:8000/api/login/
content-type: application/json

{
    "email": "abdulsalamamtech@gmail.com",
    "password": "12345678"
}



###
# Logout
POST http://127.0.0.1:8000/api/logout/
content-type: application/json
Authorization: Bearer 6|UI83SlqBp1WEr8bVHi7m8bOVl1vfUV0LZssrfmq0f48d6b9a


###
# Get login user information
GET http://127.0.0.1:8000/api/user/
content-type: application/json
Authorization: Bearer 1|xsnyqOVfWaeZCRwQbryrwOEPwFsLRSHikEPnk1b358218e7c



###
# Get login user profile
# GET http://127.0.0.1:8000/api/info
# content-type: application/json
# Authorization: Bearer 6|UI83SlqBp1WEr8bVHi7m8bOVl1vfUV0LZssrfmq0f48d6b9a



###
# Get user profile information
GET http://127.0.0.1:8000/api/profile
content-type: application/json
Authorization: Bearer 1|xsnyqOVfWaeZCRwQbryrwOEPwFsLRSHikEPnk1b358218e7c


###
# Update user profile information
PUT http://127.0.0.1:8000/api/profile
content-type: application/json
Authorization: Bearer 6|UI83SlqBp1WEr8bVHi7m8bOVl1vfUV0LZssrfmq0f48d6b9a

{
    "phone_number": "+2349091929394",
    "gender": "male",
    "dob": "2002-09-01"
}


###
# Get user social media information
GET http://127.0.0.1:8000/api/profile/socials/
content-type: application/json
Authorization: Bearer 1|xsnyqOVfWaeZCRwQbryrwOEPwFsLRSHikEPnk1b358218e7c


###
# Update user social media information
PUT http://127.0.0.1:8001/api/profile/socials/
content-type: application/json
Authorization: Bearer 2|ZKshZd0T0PUJJcbygpcZjs97cqpGR6O74QUDCCVCf78b6b72

{
    "facebook": "https://www.facebook.com/amtech",
    "github": "https://github.com/amtech",
    "twitter": "https://twitter.com/amtech/"
}



###
# Project

POST http://127.0.0.1:8000/api/project/
content-type: application/json
Authorization: Bearer 1|xsnyqOVfWaeZCRwQbryrwOEPwFsLRSHikEPnk1b358218e7c

{
    "title": "Amtech's First Project",
    "description": "This is my first project",
    "category": "Web Development",
    "status": 100000,
    "duration": 30
}
