name: Deploy Laravel SDSSN APP to VPS

on:
  push:
    branches:
      - main # Deployment happens on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up SSH Key
      run: |
        echo "${{ secrets.VPS_PRIVATE_SSH_KEY  }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to VPS
      run: |
        echo "${{ secrets.VPS}}""
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'

        # Navigate to the Laravel directory or clone the project on first run
        cd /htdocs/githubaction.sdssn.org || { git clone git@github.com:abdulsalamamtech/sdssn-app.git /htdocs/githubaction.sdssn.org && cd /htdocs/githubaction.sdssn.org/sdssn-app; }

        # Pull the latest changes
        git reset --hard
        git pull origin main

        # Install dependencies
        # composer install --no-dev --optimize-autoloader
        composer install


        # Run Laravel optimization commands
        php artisan migrate --force
        # php artisan config:cache
        # php artisan route:cache
        # php artisan view:cache

        # Ensure correct permissions
        # chown -R www-data:www-data /htdocs/githubaction.sdssn.org/sdssn-app
        # chmod -R 755 /htdocs/githubaction.sdssn.org/sdssn-app/storage /htdocs/githubaction.sdssn.org/sdssn-app/bootstrap/cache

        exit
        EOF
